### ISSUE TITLE
cutoff time in index of dfs()

### ISSUE THREAD

**Issue by grayskripko** [magnusfurugard/featuretoolsR#26] opened 2019-08-07 09:04 UTC
I use `dfs(cutoff_time_in_index=TRUE)`. I think this update https://rstudio.github.io/reticulate/news/index.html#reticulate-1-9-cran "Always call r_to_py S3 method when converting objects from Python to R" broke my code extracting multiindex as new columns with `dfs_result[[1]]$reset_index()`. Is it possible to preserve these columns after `featuretoolsR::dfs()`

**Comment by magnusfurugard** [comment] 2019-08-07 11:19
Reprex?

**Comment by grayskripko** [comment] 2019-08-07 16:15
:) sorry, I'm too lazy for it. I'll try.
The point is just to keep you posted on possible problems. At least, I was very grateful for any feedback when I worked for a similar project alone. It's impossible to cover and predict all possible problems. So I don't treat my issues as ones needed to be solved.

**Comment by magnusfurugard** [comment] 2019-08-07 16:30
> So I don't treat my issues as ones needed to be solved.

I'm sorry to sound harsh, but if this is the case then I don't think it's a good idea to file an issue. I'm making solid attempts to keep the issue count close to 0 for this repository (at least initially).

Anyway, I tried to use `cutoff_time_in_index=T` and it worked fine. Since I can't reproduce the issue and a reproducible example isn't coming I'm closing the issue for now.

(I do appreciate the comments, but I can't really help or attack the issue if there's no way to find it)

**Closed by magnusfurugard** 2019-08-07 16:30 UTC

**Comment by grayskripko** [comment] 2019-08-09 10:58
no problem, that's ok

**Comment by systats** [comment] 2019-08-30 12:32
Hi guys, I came across the same issue. This fixes it for me:

`
pacman::p_load(tidyverse, purrr, furrr, reticulate, featuretoolsR, magrittr)
np <- reticulate::import("numpy")
ind <- np$array(attr(ft_matrix[[1]], "pandas.index"))
index_df <- tibble(team_id = ind %>% map_dbl(1), date_time = ind %>% map_chr(~as.character(.x[[2]])))
`
If you have thousands of rows parrallelization or chunking might help. Let me know your work arounds or improvements to this.
