### ISSUE TITLE
featuretoolsR::list_primitives() in console

### ISSUE THREAD

**Issue by grayskripko** [magnusfurugard/featuretoolsR#4] opened 2018-12-20 07:23 UTC
```{r}
> featuretoolsR::list_primitives()
                                name                              type
1  <environment: 0x000000002bfe8ef8> <environment: 0x000000002bcdad38>
2                               <NA>                              <NA>
3                               <NA>                              <NA>
...                             ...                               ...
62                              <NA>                              <NA>

Warning message:
In format.data.frame(x, digits = digits, na.encode = FALSE) :
  corrupt data frame: columns will be truncated or padded with NAs
```

An interesting part here is that everything is ok when I tried to build this example with reprex::reprex()
But I can't work with it in my RStudio console

**Comment by magnusfurugard** [comment] 2018-12-20 17:19
Can you provide your `sessionInfo()`, as well as `reticulate::py_config()`?

**Comment by grayskripko** [comment] 2018-12-20 20:35
```{r}
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] featuretoolsR_0.1.0  RevoUtils_11.0.1     RevoUtilsMath_11.0.0

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.18       gower_0.1.2        pillar_1.3.0       compiler_3.5.1    
 [5] plyr_1.8.4         bindr_0.1.1        class_7.3-14       iterators_1.0.10  
 [9] tools_3.5.1        rpart_4.1-13       ipred_0.9-6        lubridate_1.7.4   
[13] jsonlite_1.5       tibble_1.4.2       gtable_0.2.0       nlme_3.1-137      
[17] lattice_0.20-35    pkgconfig_2.0.1    rlang_0.3.0.1      Matrix_1.2-14     
[21] foreach_1.5.0      rstudioapi_0.7     yaml_2.2.0         prodlim_2018.04.18
[25] bindrcpp_0.2.2     withr_2.1.2        dplyr_0.7.6        stringr_1.3.1     
[29] generics_0.0.2     recipes_0.1.4      stats4_3.5.1       nnet_7.3-12       
[33] grid_3.5.1         caret_6.0-81       tidyselect_0.2.4   data.table_1.11.4 
[37] reticulate_1.10    glue_1.3.0         R6_2.2.2           survival_2.42-3   
[41] lava_1.6.2         ggplot2_3.0.0      purrr_0.2.5        reshape2_1.4.3    
[45] magrittr_1.5       splines_3.5.1      MASS_7.3-50        scales_0.5.0      
[49] codetools_0.2-15   ModelMetrics_1.2.2 assertthat_0.2.0   timeDate_3043.102 
[53] colorspace_1.3-2   stringi_1.1.7      lazyeval_0.2.1     munsell_0.5.0     
[57] crayon_1.3.4      
> 
> 
> reticulate::py_config()
python:         C:\Users\srskr\ANACON~1\python.exe
libpython:      C:/Users/srskr/ANACON~1/python37.dll
pythonhome:     C:\Users\srskr\ANACON~1
version:        3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)]
Architecture:   64bit
numpy:           [NOT FOUND]

python versions found: 
 C:\Users\srskr\ANACON~1\python.exe
 C:\Users\srskr\Anaconda3\python.exe
```

**Comment by magnusfurugard** [comment] 2018-12-21 16:48
Could you try Python 2.7 or a non-Anaconda Python 3.5+?

You can change Python binary with `reticulate::use_python("path/to/binary")`, and then verify the binary is changed for the session with `reticulate::py_config()`.

**Comment by grayskripko** [comment] 2018-12-22 14:40
sorry, it's too long and doesn't affect the main functionality. I thought the solution may be known or can be found easier. You can leave this issue open if you need it as a note or close it now.
Thank you.

**Comment by magnusfurugard** [comment] 2018-12-23 10:05
Closing this issue then as I'm unable to reproduce.

**Closed by magnusfurugard** 2018-12-23 10:05 UTC

**Comment by grayskripko** [comment] 2018-12-24 00:01
I've met another one problem. Couldn't even run you demo example 
```{r}
...
es <- as_entityset(set_1, index = "key", entity_id = "set_1", id = "demo")
```
This problem and the one in the current topic was solved with an installation of the pip version of numpy, not conda
```pip install -U --force-reinstall numpy```
