### ISSUE TITLE
out of bounds when executing tidy_feature_matrix

### ISSUE THREAD

**Issue by favstats** [magnusfurugard/featuretoolsR#1] opened 2018-09-29 22:00 UTC
Hi there!

I just stumbled upon your package and I am incredibly happy someone made the effort implement this. Thanks a lot for this!

I started out with your example and unfortunately, I encountered an error when creating a tidy_feature_matrix (the idea of which I absolutely love!) 

```
# pacman::p_install_gh("magnusfurugard/featuretoolsR")

pacman::p_load(tidyverse, featuretoolsR)

# Create some mock data
set_1 <- data.frame(key = 1:100, value = sample(letters, 100, T))
set_2 <- data.frame(key = 1:100, value = sample(LETTERS, 100, T))

# Create entityset
es <- as_entityset(set_1, index = "key", entity_id = "set_1", id = "demo")

es <- es %>%
  add_entity(
    df = set_2, 
    entity_id = "set_2", 
    index = "key"
  )

es <- es %>%
  add_relationship(
    set1 = "set_1", 
    set2 = "set_2", 
    idx = "key"
  )

ft_matrix <- es %>%
  dfs(
    target_entity = "set_1", 
    trans_primitives = c("and", "divide")
  )

tidy <- tidy_feature_matrix(ft_matrix)

tidy

```

Error:

```
# Error in py_call_impl(callable, dots$args, dots$keywords) : IndexError: index 100 is out # of bounds for axis 0 with size 100
```

Through a traceback, I was able to narrow down the problem to the py_to_r function, which seems to have a problem with the 0 indexing of Python.

See here:

```
reticulate::py_to_r(ft_matrix[[1]])
```

Error:

```
# Error in py_call_impl(callable, dots$args, dots$keywords) : IndexError: index 100 is out # of bounds for axis 0 with size 100
```

Again, thank you for making this available and I totally understand that a lot of this is probably work in progress. I am just glad someone did this :)

Best,

Fabio

# Update

I tried with different data and this seems to work fine. So it seems it has something to do with the example data, maybe?

```
ft <- reticulate::import("featuretools")

es = ft$demo$load_mock_customer(return_entityset=T)

ft_matrix <- es %>%
  dfs(
    target_entity = "customers", 
    trans_primitives = c("and", "divide")
  )

tidy <- tidy_feature_matrix(ft_matrix)

tidy
```

Works just fine!

**Comment by magnusfurugard** [comment] 2018-10-01 05:15
Hi, and thanks for your very kind words. This is indeed a work in progress, so more bugs to come.. I guess.

I am unable to recreate the error (R 3.4.2 / macOS Sierra 10.12.6) . Can you send your `sessionInfo()` as well as Python environment details?

**Comment by favstats** [comment] 2018-10-12 16:04
That's odd. Just reran the entire thing, still encountering the same problem. And yes, I am able to run `ft_matrix[[1]]` just fine.

There must be some issue with my setup. It's really weird though that this only happens with the simulated dataset, different data works fine.

**Comment by magnusfurugard** [comment] 2018-10-12 16:39
(traveling, so limited ability to test on different OS')

Trying to run `featuretoolsR` on an Anaconda-installation of Python crashes the R-environment for me now. Hey, more issues! 

Could you try using a non-Anaconda version of Python? Only now realizing I've not used an Anaconda-installed Python on any of the machines.

**Comment by magnusfurugard** [comment] 2019-07-22 15:21
Closing due to age. I cannot reproduce.

**Closed by magnusfurugard** 2019-07-22 15:21 UTC
Labels: need more info
